services:

  qdrant:
    image: qdrant/qdrant:v1.16.0
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  backend:
    build: ./backend_python
    restart: always
    env_file:
      - ./backend_python/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - ./backend_python/memory:/app/memory
    depends_on:
      - qdrant
      - tts
      - stt
  tts:
    build: ./backend_python/tts
    restart: always
    env_file:
      - ./backend_python/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8002:8002"
  stt:
    build: ./backend_python/stt
    restart: always
    env_file:
      - ./backend_python/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:8001"
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3004:3000"
    env_file:
      - ./frontend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
