services:

  mem0_mcp:
    image: mem0/openmemory-mcp
    depends_on:
      - qdrant
    ports:
      - "8765:8765"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - OPENAI_API_KEY=sk-dummy-key-for-local-ollama
      - MEM0_CONFIG_PATH=/app/config.yaml
    restart: always

  mem0_UI:
    image: mem0/openmemory-ui
    depends_on:
      - qdrant
    ports:
      - "4300:3000"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - MEM0_CONFIG_PATH=/app/config.yaml
      - OPENAI_API_KEY=sk-dummy-key-for-local-ollama
    restart: always

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
