# Configuration des serveurs MCP pour Jean-Heude
mcp_servers:
  # Outil de gestion de fichiers
  #filesystem:
    #command: "npx"
    #args: ["-y", "@modelcontextprotocol/server-filesystem", "/mcp-files"]
  
  # Exemple : Recherche Web 
  brave-search:
    command: "npx"
    args: 
      - "-y"
      - "@modelcontextprotocol/server-brave-search"
    env:
      BRAVE_API_KEY: "BSArWaguTD9qp_X_x-vUikE1BKOTaV3"

  wikipedia:
    command: "npx"
    args:
      - "-y"
      - "@modelcontextprotocol/server-wikipedia"
  # Tu peux ajouter tes propres scripts Python ici aussi
  # mon-outil-perso:
  #   command: "python"
  #   args: ["mes_outils.py"]
